<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="TestDescuentos-20190826101532" tests="5" time="0.000">
	<testcase classname="TestDescuentos" name="test_comprobar_variables" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_comprobar_variables2" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_comprobar_variables3" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_comprobar_variables4" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_comprobar_variables5" time="0.000">
		<error message="1000 != 100000.0" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 39, in test_comprobar_variables5
    self.assertEqual(descuento_esperado,descuento)
AssertionError: 1000 != 100000.0
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
