<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="Test-20190804185804" tests="3" time="0.012">
	<testcase classname="Test" name="test_descuento_no_valido" time="0.001"/>
	<testcase classname="Test" name="test_nombre_casos_prueba" time="0.001"/>
	<testcase classname="Test" name="test_descuento_2" time="0.010">
		<error message="'Descuento para clientes' != 'Descuento no valido'
- Descuento para clientes
+ Descuento no valido
" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 25, in test_descuento_2
    self.assertEqual(mensaje, "Descuento no valido")
AssertionError: 'Descuento para clientes' != 'Descuento no valido'
- Descuento para clientes
+ Descuento no valido

]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
