<?xml version="1.0" ?>
<testsuite errors="1" failures="0" name="Test-20190804184831" tests="2" time="0.002">
	<testcase classname="Test" name="test_nombre_casos_prueba" time="0.000"/>
	<testcase classname="Test" name="test_descuento_no_valido" time="0.002">
		<error message="'Descuento no valido' != 0" type="AssertionError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 18, in test_descuento_no_valido
    self.assertEqual(resultado, 0)
AssertionError: 'Descuento no valido' != 0
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
