<?xml version="1.0" ?>
<testsuite errors="6" failures="0" name="TestDescuentos-20190826090031" tests="7" time="0.000">
	<testcase classname="TestDescuentos" name="test_nombre_casos_prueba" time="0.000"/>
	<testcase classname="TestDescuentos" name="test_calcular_descuento_clientes_iniciales" time="0.000">
		<error message="'module' object is not callable" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 24, in test_calcular_descuento_clientes_iniciales
    msj, descuento = descuentos(edad, valor_cotizado, dependientes)
TypeError: 'module' object is not callable
]]>		</error>
	</testcase>
	<testcase classname="TestDescuentos" name="test_calcular_descuento_especiales" time="0.000">
		<error message="'module' object is not callable" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 57, in test_calcular_descuento_especiales
    msj, descuento = descuentos(edad, valor_cotizado, dependientes)
TypeError: 'module' object is not callable
]]>		</error>
	</testcase>
	<testcase classname="TestDescuentos" name="test_calcular_descuento_familias" time="0.000">
		<error message="'module' object is not callable" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 35, in test_calcular_descuento_familias
    msj, descuento = descuentos(edad, valor_cotizado, dependientes)
TypeError: 'module' object is not callable
]]>		</error>
	</testcase>
	<testcase classname="TestDescuentos" name="test_calcular_descuento_familias_pequenias" time="0.000">
		<error message="'module' object is not callable" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 46, in test_calcular_descuento_familias_pequenias
    msj, descuento = descuentos(edad, valor_cotizado, dependientes)
TypeError: 'module' object is not callable
]]>		</error>
	</testcase>
	<testcase classname="TestDescuentos" name="test_calcular_descuento_mayores_edad" time="0.000">
		<error message="'module' object is not callable" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 79, in test_calcular_descuento_mayores_edad
    msj, descuento = descuentos(edad, valor_cotizado, dependientes)
TypeError: 'module' object is not callable
]]>		</error>
	</testcase>
	<testcase classname="TestDescuentos" name="test_calcular_descuento_no_aplica" time="0.000">
		<error message="'module' object is not callable" type="TypeError">
<![CDATA[Traceback (most recent call last):
  File "test.py", line 68, in test_calcular_descuento_no_aplica
    msj, descuento = descuentos(edad, valor_cotizado, dependientes)
TypeError: 'module' object is not callable
]]>		</error>
	</testcase>
	<system-out>
<![CDATA[]]>	</system-out>
	<system-err>
<![CDATA[]]>	</system-err>
</testsuite>
